---
######################################
# 가상 호스트 생성
# >>> roles <<<
# 1) 패키지 설치 - httpd, mod_ssl, firewalld
# 2) 서비스 설정
#   + /var/www/vhosts/ansible1/index.html - copy 사용
#     => /var/www/vhosts/{{ ansible_hostname }} 생성 
#     => index.html --> /var/www/vhosts/{{ ansible_hostname }}/index.html 배포
# 3) 서비스 기동 - httpd, firewalld
# 4) 서비스 설정 
#   + /etc/httpd/conf.d/vhost.conf - template 사용
#     => vhost.conf.j2 --> /etc/httpd/conf.d/vhost.conf
#       + handler로 실행.
# 5) 방화벽 등록 - httpd, https
######################################
- name: 가상 호스트 설정
  hosts: webservers
  gather_facts: true
  tasks:
    - name: 가상 호스트 설정 역할
      ansible.builtin.include_role:
        name: myvhost
